import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { MessageCircle, Plus, X, Sparkles, Send, Loader2, Wand2, CheckCheck, Clock, Inbox, Reply } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/api/client";
import { useLeads, updateLeadStatus, type Lead } from "@/lib/leads-client";

export const Route = createFileRoute("/app/messages")({
  component: WhatsappStudio,
});

const intents = ["Quick check-in", "Pricing follow-up", "Demo reminder", "Re-engage"];

type Status = "draft" | "sent" | "delivered" | "read" | "replied" | "failed";

interface Row {
  id: string;
  lead_id: string | null;
  body: string;
  status: Status;
  sent_at: string | null;
  delivered_at: string | null;
  read_at: string | null;
  created_at: string;
}

function WhatsappStudio() {
  const { leads, reload: reloadLeads } = useLeads();
  const [rows, setRows] = useState<Row[]>([]);
  const [composing, setComposing] = useState(false);

  async function refresh() {
    const data = await api.getWhatsapps() as Row[];
    if (data) setRows(data);
  }
  useEffect(() => { refresh(); }, []);

  const groups = useMemo(() => {
    const g: Record<string, Row[]> = { draft: [], sent: [], delivered: [], read: [], replied: [] };
    for (const r of rows) (g[r.status === "failed" ? "draft" : r.status] ??= []).push(r);
    return g;
  }, [rows]);

  const lanes: { key: string; label: string; tint: string; Icon: typeof Send }[] = [
    { key: "draft", label: "Drafts", tint: "gradient-soft", Icon: Wand2 },
    { key: "sent", label: "Sent", tint: "gradient-sky", Icon: Send },
    { key: "delivered", label: "Delivered", tint: "gradient-mint", Icon: Inbox },
    { key: "read", label: "Read", tint: "gradient-peach", Icon: CheckCheck },
    { key: "replied", label: "Replied", tint: "gradient-brand", Icon: Reply },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">WhatsApp follow-ups</h1>
          <p className="mt-1 text-sm text-muted-foreground">Personalized WhatsApp nudges generated by AI. Track delivery and replies in real-time.</p>
        </div>
        <button onClick={() => setComposing(true)} className="inline-flex items-center gap-2 rounded-xl gradient-brand px-4 py-2 text-sm font-medium text-white shadow-glow">
          <Plus className="h-4 w-4" /> New broadcast
        </button>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">
        {lanes.map(({ key, label, tint, Icon }) => (
          <div key={key} className="flex min-h-[280px] flex-col rounded-2xl border border-border bg-card/70 p-3 shadow-soft">
            <div className="mb-3 flex items-center justify-between px-1">
              <div className="flex items-center gap-2">
                <span className={`grid h-7 w-7 place-items-center rounded-lg ${tint}`}><Icon className="h-3.5 w-3.5 text-foreground/80" /></span>
                <div className="text-sm font-semibold">{label}</div>
              </div>
              <div className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">{groups[key]?.length ?? 0}</div>
            </div>
            <div className="space-y-2">
              {(groups[key] ?? []).map((r) => {
                const lead = leads.find((l) => l.id === r.lead_id);
                return (
                  <div key={r.id} className="rounded-xl border border-border bg-background p-3">
                    <div className="flex items-center gap-2">
                      <div className="grid h-7 w-7 place-items-center rounded-full gradient-mint text-[10px] font-semibold">
                        {lead?.name.split(" ").map((p) => p[0]).join("").slice(0,2)}
                      </div>
                      <div className="min-w-0 flex-1 text-xs">
                        <div className="truncate font-medium">{lead?.name ?? "—"}</div>
                        <div className="truncate text-muted-foreground">{lead?.phone ?? ""}</div>
                      </div>
                    </div>
                    <div className="mt-2 rounded-lg bg-success/10 p-2 text-xs leading-snug">{r.body}</div>
                    <div className="mt-2 flex items-center justify-between text-[11px] text-muted-foreground">
                      <span><Clock className="mr-1 inline h-3 w-3" />{new Date(r.created_at).toLocaleTimeString()}</span>
                      {r.status === "draft" && (
                        <button onClick={() => sendOne(r, refresh, reloadLeads)} className="inline-flex items-center gap-1 rounded-md gradient-brand px-2 py-0.5 text-white">
                          <Send className="h-3 w-3" /> Send
                        </button>
                      )}
                    </div>
                  </div>
                );
              })}
              {(groups[key]?.length ?? 0) === 0 && (
                <div className="rounded-xl border border-dashed border-border p-4 text-center text-xs text-muted-foreground">No items</div>
              )}
            </div>
          </div>
        ))}
      </div>

      {composing && <Composer leads={leads} onClose={() => setComposing(false)} onDone={() => { setComposing(false); refresh(); }} />}
    </div>
  );
}

async function sendOne(r: Row, refresh: () => void, reloadLeads: () => void) {
  const now = new Date().toISOString();
  await api.updateWhatsappStatus({ id: r.id, status: "sent", sent_at: now });
  refresh();
  setTimeout(async () => {
    await api.updateWhatsappStatus({ id: r.id, status: "delivered", delivered_at: new Date().toISOString() });
    refresh();
    setTimeout(async () => {
      await api.updateWhatsappStatus({ id: r.id, status: "read", read_at: new Date().toISOString() });
      refresh();
      if (Math.random() > 0.6) {
        setTimeout(async () => {
          await api.updateWhatsappStatus({ id: r.id, status: "replied" });
          refresh();
        }, 1800);
      }
    }, 1300);
  }, 700);
  if (r.lead_id) {
    await updateLeadStatus(r.lead_id, "contacted");
    reloadLeads();
  }
  toast.success("WhatsApp message sent");
}

function Composer({ leads, onClose, onDone }: { leads: Lead[]; onClose: () => void; onDone: () => void }) {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [intent, setIntent] = useState(intents[0]);
  const [busy, setBusy] = useState(false);
  const [search, setSearch] = useState("");
  const eligible = leads.filter((l) => l.phone);
  const filtered = eligible.filter((l) => !search || l.name.toLowerCase().includes(search.toLowerCase()));

  function toggle(id: string) { setSelected((s) => { const n = new Set(s); n.has(id) ? n.delete(id) : n.add(id); return n; }); }
  function selectAll() { setSelected(new Set(filtered.map((l) => l.id))); }

  async function generate() {
    if (!selected.size) { toast.error("Pick at least one recipient"); return; }
    setBusy(true);
    try {
      const targets = leads.filter((l) => selected.has(l.id));
      const results = await Promise.all(
        targets.map(async (lead) => {
          const out = await api.aiComposeWhatsapp({
            lead: { id: lead.id, name: lead.name, company: lead.company, email: lead.email, city: lead.city, status: lead.status, score: lead.score, value: lead.value, source: lead.source, notes: lead.notes },
            intent,
          });
          return { lead_id: lead.id, body: out.body, status: "draft" };
        }),
      );
      await api.insertWhatsapps(results);
      toast.success(`Drafted ${results.length} messages`);
      onDone();
    } catch (e) {
      toast.error("AI failed", { description: (e as Error).message });
    } finally { setBusy(false); }
  }

  return (
    <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-sm">
      <div className="grid w-full max-w-3xl grid-rows-[auto_1fr_auto] overflow-hidden rounded-2xl border border-border bg-card shadow-elegant">
        <div className="flex items-center justify-between border-b border-border px-5 py-3">
          <div className="flex items-center gap-2"><MessageCircle className="h-4 w-4" /><div className="text-sm font-semibold">New WhatsApp broadcast</div></div>
          <button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-md hover:bg-accent"><X className="h-4 w-4" /></button>
        </div>
        <div className="grid grid-cols-1 gap-4 p-5 md:grid-cols-2">
          <div>
            <div className="flex items-center justify-between">
              <div className="text-xs font-medium text-muted-foreground">Recipients ({selected.size}/{eligible.length})</div>
              <button onClick={selectAll} className="text-xs text-primary">Select all</button>
            </div>
            <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search…" className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-1.5 text-sm" />
            <div className="mt-2 max-h-72 space-y-1 overflow-y-auto rounded-xl border border-border bg-background p-2">
              {filtered.slice(0, 60).map((l) => (
                <label key={l.id} className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-muted/60">
                  <input type="checkbox" checked={selected.has(l.id)} onChange={() => toggle(l.id)} />
                  <span className="flex-1 truncate">{l.name} <span className="text-xs text-muted-foreground">· {l.phone}</span></span>
                </label>
              ))}
            </div>
          </div>
          <div className="space-y-3">
            <div>
              <div className="text-xs font-medium text-muted-foreground">Message intent</div>
              <div className="mt-1 flex flex-wrap gap-1.5">
                {intents.map((g) => (
                  <button key={g} onClick={() => setIntent(g)} className={`rounded-full border px-3 py-1 text-xs ${intent === g ? "gradient-brand border-transparent text-white" : "border-border bg-background hover:bg-accent"}`}>{g}</button>
                ))}
              </div>
            </div>
            <div className="rounded-xl border border-border bg-background p-3 text-xs text-muted-foreground">
              <div className="flex items-center gap-1.5 font-medium text-foreground"><Sparkles className="h-3.5 w-3.5" /> Personalized per recipient</div>
              <p className="mt-1">AI writes a unique 1-3 sentence message for each lead. Edit any draft before sending.</p>
            </div>
          </div>
        </div>
        <div className="flex items-center justify-end gap-2 border-t border-border px-5 py-3">
          <button onClick={generate} disabled={busy} className="inline-flex items-center gap-2 rounded-xl gradient-brand px-4 py-2 text-sm font-medium text-white shadow-glow disabled:opacity-60">
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />} Generate drafts
          </button>
        </div>
      </div>
    </div>
  );
}
